const ERROR_CODES = {
  UNKOWN_ERROR : "UNKOWN_ERROR",
  SERVER_ERROR : "SERVER_ERROR",
  VALIDATION_ERROR : "VALIDATION_ERROR",
  MISSING_FIELD : "MISSING_FIELD",

  EXPIRED_OTP : "EXPIRED_OTP",
  INVALID_SESSION : "INVALID_SESSION",
  UNUTHORIZE_ERROR : "UNUTHORIZE_ERROR", 
  PLEASE_WAIT : "PLEASE_WAIT",
  INVALID_TOKEN : "INVALID_TOKEN",
  REACHED_MAX_ATTEMPS : "REACHED_MAX_ATTEMPS", 

  EMAIL_ALREADY_EXISTS : "EMAIL_ALREADY_EXISTS",
  INVALID_PASSWORD : "INVALID_PASSWORD",
  INVALID_EMAIL_FORMAT : "INVALID_EMAIL_FORMAT",

  FIELD_TOO_LONG : "FIELD_TOO_LONG",
  INVALID_RANGE : "INVALID_RANGE",
  INVALID_ENUM_VALUE : "INVALID_ENUM_VALUE",
}

module.exports = ERROR_CODES;