const ERROR_CODES = {
  UNKOWN_ERROR : "UNKOWN_ERROR",
  SERVER_ERROR : "SERVER_ERROR",
  VALIDATION_ERROR : "VALIDATION_ERROR",
  MISSING_FIELD : "MISSING_FIELD",

  EXPIRED_OTP : "EXPIRED_OTP",
  INVALID_TOKEN : "INVALID_TOKEN",

  EMAIL_ALREADY_EXISTS : "EMAIL_ALREADY_EXISTS",
  INVALID_PASSWORD : "INVALID_PASSWORD",
  INVALID_EMAIL_FORMAT : "INVALID_EMAIL_FORMAT",
}

module.exports = ERROR_CODES;