const ERROR_CODES = {
  UNKOWN_ERROR : "UNKWON_ERROR",
  SERVER_ERROR : "SERVER_ERROR",
  EMAIL_ALREADY_EXISTS : "EMAIL_ALREADY_EXISTS",
  INVALID_PASSWORD : "INVALID_PASSWORD",
  MISSING_FIELD : "MISSING_FIELD",
  MISSING_FIRSTNAME : "MISSING_FIRSTNAME",
  MISSING_LASTNAME : "MISSING_LASTNAME",
  MISSING_EMAIL : "MISSING_EMAIL",
  MISSING_PASSWORD : "MISSING_PASSWORD",
}

module.exports = ERROR_CODES;